Pages/Events/Create.cshtml.cs
using gcsharpRPC.Models;
using gcsharpRPC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace gcsharpRPC.Pages.Polls
{
    public class CreatePollPageModel : PageModel
    {
        private readonly PollService _service;

        private readonly ILogger _logger;

        [BindProperty]
        public Poll Poll { get; set; }

        [BindProperty]
        public DateTime[] PollOptionDates { get; set; }

        [BindProperty]
        public string[] PollOptionStartTimes { get; set; }

        [BindProperty]
        public string[] PollOptionEndTimes { get; set; }
        
        public CreatePollPageModel(PollService pollService,
                            ILogger<CreatePollPageModel> logger)
        {
            _service = pollService;
            _logger = logger;
        }

        public IActionResult OnGet() {
            if (HttpContext.Session.GetString("username") is null) 
            {
                return Redirect("/Login");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync() {
            if (HttpContext.Session.GetString("username") is null)
            {
                return Redirect("/Login");
            }

            _logger.LogInformation("Called OnPostAsync!!");

            if (ModelState.IsValid) {
                _logger.LogInformation("Model Valid");
            }

            if (Poll is not null) {
                _logger.LogInformation("Poll is not null");
            }

            // if (PollOptions is not null) {
            //     _logger.LogInformation("PollOptions is not null");
            //     // _logger.LogInformation(PollOptions.StartTime);
            // }

            // if (PollOptions.Length == 0)
            // {
            //     _logger.LogInformation("PollOptions is zero");
            // }
            // else
            // {
            //     _logger.LogInformation("PollOptions is not zero");
            // }

            PollOption[] PollOptions = new PollOption[PollOptionDates.Length];

            for (int i=0; i<PollOptionEndTimes.Length; ++i)
            {
                _logger.LogInformation("--> " + PollOptionDates[i]);
                _logger.LogInformation("--> " + PollOptionStartTimes[i]);
                _logger.LogInformation("--> " + PollOptionEndTimes[i]);

                PollOptions[i] = new PollOption {
                    Date = PollOptionDates[i],
                    StartTime = PollOptionStartTimes[i],
                    EndTime = PollOptionEndTimes[i]
                };
            }

            if (ModelState.IsValid && Poll is not null) {
                await _service.CreatePollAsync(Poll, PollOptions);

                return RedirectToPage("Index", new { id = Poll.Id });
            }

            return Page();
        }
    }
}

Pages/Events/Index.cshtml.cs
using Microsoft.EntityFrameworkCore;
using gcsharpRPC.Models;
using gcsharpRPC.Services;
using gcsharpRPC.Helpers    ;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace gcsharpRPC.Pages.Polls
{
    public class GetPollPageModel : PageModel
    {
        private readonly ILogger<GetPollPageModel> _logger;

        private readonly PollService _service = null;
        
        public Poll Poll { get; set; }

        public string _session;

        public GetPollPageModel(PollService service, ILogger<GetPollPageModel> logger)
        {
            _service = service;
            _logger = logger;
        }

        public async Task OnGetAsync(int id)
        {
            _session = HttpContext.Session.GetString("username");

            _logger.LogInformation($"Call OnGetAsync IndexModel with ID: {id}");
            Poll = await _service.GetPollAsync(id);
        }

        public async Task<IActionResult> OnPostCloseAsync(int id)
        {
            _logger.LogInformation($"Call OnPostCloseAsync with ID {id}");
            int idClosed = await _service.ClosePollAsync(id);
            return RedirectToPage("/Events/Index", new { id = idClosed.ToString() });
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            if (HttpContext.Session.GetString("username") is null) {
                return RedirectToPage("/Login");
            }

            _logger.LogInformation($"Call OnDeleteAsync with ID {id}");
            int idDeleted = await _service.DeletePollAsync(id);
            return RedirectToPage("/Events/Index", new { id = idDeleted.ToString() });;
        }
    }
}

Pages/Events/Join.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using gcsharpRPC.Services;
using gcsharpRPC.Models;

namespace gcsharpRPC.Pages.Polls
{
    public class JoinPollPageModel : PageModel
    {
        private readonly PollService _service;

        [Required]
        public Poll Poll { get; set; }

        [BindProperty]
        [Required, MinLength(1)]
        public string Name { get; set; }

        [BindProperty]
        [Required, EmailAddress]
        public string Email { get; set; }

        [BindProperty]
        [Required, MinLength(1)]
        public int[] SelectedPollOptionIds { get; set; }

        public JoinPollPageModel(PollService service)
        {
            _service = service;
        }

        public async Task OnGetAsync(Guid guid)
        {
            Poll = await _service.GetPollByGuidAsync(guid);
        }

        public async Task<IActionResult> OnPostAsync(Guid guid) {
            Poll = await _service.GetPollByGuidAsync(guid);

            if (ModelState.IsValid)
            {
                await _service.VotePollAsync(guid, Name, Email, SelectedPollOptionIds);
            }

            return Page();
        }
    }
}

Pages/Events/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using gcsharpRPC.Helpers;
using gcsharpRPC.Models;

namespace MyApp.Namespace
{
    public class ListModel : PageModel
    {
        private readonly ILogger<ListModel> _logger;

        public DbSet<Poll> Polls { get; set; }

        public ListModel(TrungContext pc, ILogger<ListModel> logger)
        {
            Polls = pc.Polls;
            _logger = logger;
        }
    }
}

Pages/Events/Create.cshtml
@page
@model gcsharpRPC.Pages.Polls.CreatePollPageModel
@{
    ViewData["Title"] = "Create Events";
}
<h1>Create An Event</h1>

<form method="POST">
    <div class="form-group">
        <label asp-for="Poll.Title"></label>
        <input type="text" asp-for="Poll.Title" class="form-control" />
        <span asp-validation-for="Poll.Title" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <label asp-for="Poll.Location"></label>
        <input type="text" asp-for="Poll.Location" class="form-control" />
        <span asp-validation-for="Poll.Location" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Poll.CloseDate">Close Date(mm/dd/yy)</label>
        <input id="clsDate" type="date" asp-for="Poll.CloseDate" class="form-control" />
    </div>

    <div style="height:20px;"></div>

    <h5>Add poll options</h5>
    <div class="form-group">
        <label for="fromDate">From(mm/dd/yy)</label>
        <input id="fromDate" type="date" class="form-control" />
    </div>
    <div class="form-group mb-2">
        <label for="toDate">To(mm/dd/yy)</label>
        <input id="toDate" type="date" class="form-control" />
    </div>
    <button type="button" class="btn btn-outline-primary btn-sm mb-3" onclick="addOptions()">Add options</button>
    
    <h5>Poll options</h5>
    <div id="option-container">
    </div>

    <button type="submit" class="btn btn-primary btn-sm mt-2 mb-2">Create</button>
</form>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const fromDateCtl = document.getElementById("fromDate");
        const toDateCtl = document.getElementById("toDate");

        const currentDate = new Date();
        fromDateCtl.valueAsDate = currentDate;
        toDateCtl.valueAsDate = currentDate;

        const next7days = new Date();
        next7days.setDate(currentDate.getDate() + 7);
        document.getElementById("clsDate").valueAsDate = next7days;

        fromDateCtl.addEventListener("change", () => {
            const fromDate = fromDateCtl.valueAsDate;
            const toDate = toDateCtl.valueAsDate;

            if (toDate < fromDate)
                toDateCtl.value = fromDateCtl.value;
        });
    });  
    function addOptions() {
        const fromDate = document.getElementById("fromDate").valueAsDate;
        const toDate = document.getElementById("toDate").valueAsDate;

        let existingValues = $("#option-container > div >  input")
            .map((_i, option) => option.valueAsDate.toString())
            .get();
        
        for (let currentDate = fromDate; currentDate <= toDate; currentDate.setDate(currentDate.getDate() + 1)) {
            if (!existingValues.includes(currentDate.toString()))
                addOption(currentDate);
        }
        
        reorderPollOptions();
    }
    function addOption(value) {
        // const defaultStartTime = "00:00";
        // const defaultEndTime = "24:59";

        const container = document.createElement("div");
        container.className = "poll-option d-flex mb-1";

        let input = document.createElement("input");
        input.className = "form-control date-option";
        input.name = "PollOptionDates";
        input.type = "date";
        input.valueAsDate = value;
        input.addEventListener("change", reorderPollOptions);
        container.append(input);

        input = document.createElement("input");
        input.className = "form-control time-option";
        input.name = "PollOptionStartTimes";
        // input.value = defaultStartTime;
        // input.addEventListener("change", reorderPollOptions);
        container.append(input);

        input = document.createElement("input");
        input.className = "form-control time-option";
        input.name = "PollOptionEndTimes";
        // input.value = defaultEndTime;
        // input.addEventListener("change", reorderPollOptions);
        container.append(input);

        const delButton = document.createElement("button");
        delButton.className = "btn btn-outline-danger btn-sm ms-1";
        delButton.textContent = "Remove";
        delButton.type = "button";
        delButton.addEventListener("click", function() {
            $(".time-option").each(function() {
                console.log("++ " + $(this).value);
            });
            container.remove()
        });
        container.append(delButton);
        
        document.getElementById("option-container").append(container);

        $(".time-option").each(function() {
            console.log("--> " + $(this).val());
            $(this).timepicker();
        });
    }
    function reorderPollOptions() {
        $("#option-container > .date-option").sort(function(a, b) {
            const dateA = a.childNodes[0].valueAsDate;
            const dateB = b.childNodes[0].valueAsDate;

            return dateA - dateB;
        }).appendTo($("#option-container"));
    }
</script>

Pages/Events/Index.cshtml
@page "{id:int}"
@using gcsharpRPC.Pages.Shared;
@model gcsharpRPC.Pages.Polls.GetPollPageModel
@{
    var pollId = RouteData.Values["id"];
}

<h2>@(Model.Poll?.Title ?? "Not Found")</h2>

@if (Model.Poll is not null)
{
    <h5>Actions</h5>
    <form method="POST">
        @if (Model._session is not null)
        {
            <a class="btn btn-warning btn-sm ms-1" type="submit" asp-page-handler="Delete" asp-route-id="@Model.Poll.Id">Delete</a>
        }
        @{
            var guid = Model.Poll.PollGuid.ToString("N");
            <a class="btn btn-primary btn-sm ms-1" asp-page="Join" asp-route-guid="@guid">Join</a>
        }
    </form>

    @* <h6>Close</h6>
    <form method="POST">
        <button type="submit" asp-page-handler="ToggleClose" asp-route-id="@Model.Poll.Id">Close</button>
    </form> *@
}

<div class="mt-3">
    <partial name="_BackToListBtn" />
</div>

Pages/Events/Join.cshtml
@page "{guid:Guid}"
@using gcsharpRPC.Pages.Shared;
@model gcsharpRPC.Pages.Polls.JoinPollPageModel
@{
    ViewData["Title"] = Model.Poll?.Title;
}
@section scripts{
   <partial name="_ValidationScriptsPartial" />
}

<h2>@(Model.Poll?.Title ?? "Not found")</h2>

@if (Model.Poll is not null)
{
    <h5>Location</h5>
    <div class="card">
    <div class="card-body">
        @Html.DisplayFor(model => model.Poll.Location)
    </div>
    </div>

    <div>
        <dl class="row">
            <dd class="col-sm-10">
                <form id="" method="POST">
                    <partial name="_PollOptionTable" model="_PollOptionTableModel.Create(Model.Poll)" />

                    @if (!Model.Poll.CloseDate.HasValue)
                    {
                        <h5 class="mt-4">Participate</h5>

                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Email"></label>
                            <input type="text" asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <input type="submit" class="btn btn-primary mt-2 mb-2 btn-sm" value="Join"/>
                    }
                    else
                    {
                        <div class="alert alert-success" role="alert">
                            This poll was closed on @Html.DisplayFor(model => model.Poll.CloseDate)
                        </div>
                    }
                </form>
            </dd>
        </dl>
    </div>
}

Pages/Events/List.cshtml
@page
@model MyApp.Namespace.ListModel
@{
    ViewData["Title"] = "Admin";
}

<h2>All Events</h2>

<div>
    <a class="btn btn-primary btn-sm mb-2" asp-page="../Events/Create">Create Events</a>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">Closed Date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Polls)
                {
                    var pollGuid = item.PollGuid.ToString("N");
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location)
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.CloseDate)</td>
                        <td>
                            <a class="btn btn-secondary btn-sm ms-1 mb-1" asp-page="/Events/Index" asp-route-id="@item.Id">View</a>
                            <a class="btn btn-secondary btn-sm ms-1 mb-1" asp-page="/Events/Join" asp-route-guid="@pollGuid">Join</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>